"use strict";
const bcrypt = require("bcrypt");

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    const passwordHash = await bcrypt.hash("examplePassword", 10);
    await queryInterface.bulkInsert(
      "users",
      [
        // élèves
        {
          firstname: "Luke",
          lastname: "Skywalker",
          gender: "M",
          birthdate: "1990-01-01",
          adress: "1 rue de la paix",
          city: "Paris",
          zipcode: "75000",
          email: "luke@gmail.com",
          ine: "1234567891C",
          password: passwordHash,
          phone: "0606060606",
          // id_class: 1,
          // id_establishment : 1,
          id_role: 3,
          first_tutor: 21,
          second_tutor: 22,
          id: 1,
        },
        {
          firstname: "Rey",
          lastname: "Skywalker",
          gender: "F",
          birthdate: "1995-10-21",
          adress: "7 rue de l'étoile",
          city: "Jakku",
          zipcode: "77777",
          email: "rey@gmail.com",
          ine: "1234567891D",
          password: passwordHash,
          phone: "0607080901",
          id_role: 3,
          first_tutor: 4,
          second_tutor: 5,
          id: 2,
        },
        {
          firstname: "Kylo",
          lastname: "Ren",
          gender: "M",
          birthdate: "1991-09-15",
          adress: "16 Darkside Avenue",
          city: "Starkiller Base",
          zipcode: "55555",
          email: "kyloren@gmail.com",
          ine: "1234567891F",
          password: passwordHash,
          phone: "0607000102",
          id_role: 3,
          first_tutor: 6,
          second_tutor: 7,
          id: 3,
        },
        {
          firstname: "Rose",
          lastname: "Tico",
          gender: "F",
          birthdate: "1993-05-04",
          adress: "9 Resistance Road",
          city: "D'Qar",
          zipcode: "44444",
          email: "rosetico@gmail.com",
          ine: "1234567891G",
          password: passwordHash,
          phone: "0607101102",
          id_role: 3,
          first_tutor: 8,
          second_tutor: 9,
          id: 4,
        },
        {
          firstname: "Maz",
          lastname: "Kanata",
          gender: "F",
          birthdate: "1988-04-02",
          adress: "2 Castle Street",
          city: "Takodana",
          zipcode: "33333",
          email: "mazkanata@gmail.com",
          ine: "1234567891H",
          password: passwordHash,
          phone: "0607201202",
          id_role: 3,
          first_tutor: 10,
          second_tutor: 11,
          id: 5,
        },
        {
          firstname: "Qui-Gon",
          lastname: "Jinn",
          gender: "M",
          birthdate: "1986-03-19",
          adress: "23 Jedi Temple Drive",
          city: "Coruscant",
          zipcode: "22222",
          email: "quigonjinn@gmail.com",
          ine: "1234567891I",
          password: passwordHash,
          phone: "0607301302",
          id_role: 3,
          first_tutor: 12,
          second_tutor: 13,
          id: 6,
        },
        {
          firstname: "Mace",
          lastname: "Windu",
          gender: "M",
          birthdate: "1985-06-14",
          adress: "24 Jedi Council Avenue",
          city: "Coruscant",
          zipcode: "22221",
          email: "macewindu@gmail.com",
          ine: "1234567891J",
          password: passwordHash,
          phone: "0607401402",
          id_role: 3,
          first_tutor: 14,
          second_tutor: 15,
          id: 7,
        },
        {
          firstname: "Count",
          lastname: "Dooku",
          gender: "M",
          birthdate: "1980-10-10",
          adress: "1 Sith Lords Lane",
          city: "Serenno",
          zipcode: "11111",
          email: "countdooku@gmail.com",
          ine: "1234567891K",
          password: passwordHash,
          phone: "0607501502",
          id_role: 3,
          first_tutor: 16,
          second_tutor: 17,
          id: 8,
        },
        {
          firstname: "Jyn",
          lastname: "Erso",
          gender: "F",
          birthdate: "1992-02-20",
          adress: "2 Rebellion Path",
          city: "Yavin 4",
          zipcode: "99999",
          email: "jynerso@gmail.com",
          ine: "1234567891L",
          password: passwordHash,
          phone: "0607601602",
          id_role: 3,
          first_tutor: 18,
          second_tutor: 19,
          id: 9,
        },
        {
          firstname: "Cassian",
          lastname: "Andor",
          gender: "M",
          birthdate: "1991-04-30",
          adress: "3 Espionage Way",
          city: "Yavin 4",
          zipcode: "99998",
          email: "cassianandor@gmail.com",
          ine: "1234567891M",
          password: passwordHash,
          phone: "0607701702",
          id_role: 3,
          // first_tutor: 20,
          // second_tutor: 21,
          id: 10,
        },
        {
          firstname: "Ryu",
          lastname: "Hoshi",
          gender: "M",
          birthdate: "1985-07-21",
          adress: "1 Hadouken Way",
          city: "Suzaku Castle",
          zipcode: "10001",
          email: "ryu@hadouken.com",
          ine: "SF1234561A",
          password: passwordHash,
          phone: "0607801802",
          id_role: 3,
          first_tutor: 22,
          second_tutor: 23,
          id: 11,
        },
        {
          firstname: "Chun-Li",
          lastname: "Xiang",
          gender: "F",
          birthdate: "1988-03-01",
          adress: "2 Spinning Bird Avenue",
          city: "Shanghai",
          zipcode: "10002",
          email: "chunli@kikoken.com",
          ine: "SF1234562B",
          password: passwordHash,
          phone: "0607901902",
          id_role: 3,
          first_tutor: 24,
          second_tutor: 25,
          id: 12,
        },
        {
          firstname: "Ken",
          lastname: "Masters",
          gender: "M",
          birthdate: "1985-02-14",
          adress: "3 Shoryuken Drive",
          city: "San Francisco",
          zipcode: "10003",
          email: "ken@shoryuken.com",
          ine: "SF1234563C",
          password: passwordHash,
          phone: "0608002002",
          id_role: 3,
          first_tutor: 26,
          second_tutor: 27,
          id: 13,
        },
        {
          firstname: "Cammy",
          lastname: "White",
          gender: "F",
          birthdate: "1974-01-06",
          adress: "7 Spiral Arrow Lane",
          city: "London",
          zipcode: "30001",
          email: "cammy@delta.com",
          ine: "SF1234567G",
          password: passwordHash,
          phone: "0608402402",
          id_role: 3,
          first_tutor: 28,
          second_tutor: 29,
          id: 14,
        },
        {
          firstname: "Blanka",
          lastname: "Jimenez",
          gender: "M",
          birthdate: "1966-02-12",
          adress: "8 Electric Jungle Road",
          city: "Brazil",
          zipcode: "30002",
          email: "blanka@amazon.com",
          ine: "SF1234568H",
          password: passwordHash,
          phone: "0608502502",
          id_role: 3,
          first_tutor: 30,
          second_tutor: 31,
          id: 15,
        },
        {
          firstname: "Sakura",
          lastname: "Kasugano",
          gender: "F",
          birthdate: "1983-03-15",
          adress: "9 Schoolyard Street",
          city: "Tokyo",
          zipcode: "30003",
          email: "sakura@shunpukyaku.com",
          ine: "SF1234569I",
          password: passwordHash,
          phone: "0608602602",
          id_role: 3,
          first_tutor: 32,
          second_tutor: 33,
          id: 16,
        },
        {
          firstname: "Vega",
          lastname: "Cortez",
          gender: "M",
          birthdate: "1967-01-27",
          adress: "10 Claw Crescent",
          city: "Spain",
          zipcode: "30004",
          email: "vega@rose.com",
          ine: "SF1234570J",
          password: passwordHash,
          phone: "0608702702",
          id_role: 3,
          first_tutor: 34,
          second_tutor: 35,
          id: 17,
        },
        {
          firstname: "Balrog",
          lastname: "Jones",
          gender: "M",
          birthdate: "1968-09-04",
          adress: "11 Boxing Ring Avenue",
          city: "Las Vegas",
          zipcode: "30005",
          email: "balrog@boxing.com",
          ine: "SF1234571K",
          password: passwordHash,
          phone: "0608802802",
          id_role: 3,
          first_tutor: 36,
          second_tutor: 37,
          id: 18,
        },
        {
          firstname: "Ibuki",
          lastname: "Yamamoto",
          gender: "F",
          birthdate: "1989-12-06",
          adress: "12 Ninja Way",
          city: "Osaka",
          zipcode: "30006",
          email: "ibuki@kunai.com",
          ine: "SF1234572L",
          password: passwordHash,
          phone: "0608902902",
          id_role: 3,
          first_tutor: 38,
          second_tutor: 39,
          id: 19,
        },
        {
          firstname: "Karin",
          lastname: "Kanzuki",
          gender: "F",
          birthdate: "1982-09-15",
          adress: "13 Elite Mansion Road",
          city: "Tokyo",
          zipcode: "30007",
          email: "karin@ojou.com",
          ine: "SF1234573M",
          password: passwordHash,
          phone: "0609003002",
          id_role: 3,
          first_tutor: 40,
          second_tutor: 41,
          id: 20,
        },
        
        // tuteurs
        {
          firstname: "Anakin",
          lastname: "Skywalker",
          gender: "M",
          birthdate: "1988-01-31",
          adress: "10 rue des bois",
          city: "Marseille",
          zipcode: "13000",
          email: "anakin@gmail.com",
          password: passwordHash,
          phone: "0690486933",
          // id_establishment : 1,
          // id_class : 1,
          id_role: 2,
          id: 21,
        },
        {
          firstname: "Padmé",
          lastname: "Amidala",
          gender: "F",
          birthdate: "1984-09-11",
          adress: "3 rue du Pont",
          city: "Lyon",
          zipcode: "69000",
          email: "padme@gmail.com",
          password: passwordHash,
          phone: "0676341346",
          // id_establishment : 1,
          //id_class: 1,
          id_role: 2,
          id: 22,
        },
        {
          firstname: "Finn",
          lastname: "FN-2187",
          gender: "M",
          birthdate: "1990-08-17",
          adress: "8 boulevard de la liberté",
          city: "Jakku",
          zipcode: "77778",
          email: "finn@gmail.com",
          password: passwordHash,
          phone: "0608050403",
          id_role: 2,
          id: 23,
        },
        {
          firstname: "Poe",
          lastname: "Dameron",
          gender: "M",
          birthdate: "1987-07-19",
          adress: "9 rue du soleil",
          city: "Yavin",
          zipcode: "77779",
          email: "poe@gmail.com",
          password: passwordHash,
          phone: "0706050403",
          id_role: 2,
          id: 24,
        },
        // admin
        {
          firstname: "Maitre",
          lastname: "Yoda",
          gender: "M",
          birthdate: "1984-06-29",
          adress: "4 chemin des pres",
          city: "Rouen",
          zipcode: "76000",
          email: "yoda@gmail.com",
          password: passwordHash,
          phone: "0712345678",
          // id_establishment : 1,
          //id_class: 1,
          id_role: 4,
          id: 25,
        },
        
        
        // professeurs
        {
          firstname: "Obi-Wan",
          lastname: "Kenobi",
          gender: "M",
          birthdate: "1980-03-03",
          adress: "150 avenue des champs",
          city: "Bordeaux",
          zipcode: "33000",
          email: "obiwan@gmail.com",
          password: passwordHash,
          phone: "0789098754",
          ine: "1234567891E",
          // id_establishment : 1,
          //id_class: 1,
          id_role: 5,
          id_status: 1,
          id: 26,
        },
        {
          firstname: "Leia",
          lastname: "Organa",
          gender: "F",
          birthdate: "1986-10-21",
          adress: "5 rue de la Liberté",
          city: "Tatooine",
          zipcode: "12345",
          email: "leia@gmail.com",
          password: passwordHash,
          phone: "0987654321",
          id_role: 5,
          id_status: 1,
          id: 27,
        },
        {
          firstname: "Han",
          lastname: "Solo",
          gender: "M",
          birthdate: "1982-05-12",
          adress: "15 boulevard des étoiles",
          city: "Coruscant",
          zipcode: "54321",
          email: "han@gmail.com",
          password: passwordHash,
          phone: "0987654321",
          id_role: 5,
          id_status: 1,
          id: 28,
        },
        {
          firstname: "Chewbacca",
          lastname: "Chewie",
          gender: "M",
          birthdate: "1995-11-15",
          adress: "8 allée des wookies",
          city: "Kashyyyk",
          zipcode: "67890",
          email: "chewie@gmail.com",
          password: passwordHash,
          phone: "0987654321",
          id_role: 5,
          id_status: 1,
          id: 29,
        },
        {
          firstname: "Lando",
          lastname: "Calrissian",
          gender: "M",
          birthdate: "1981-12-25",
          adress: "20 rue du jeu de sabacc",
          city: "Bespin",
          zipcode: "98765",
          email: "lando@gmail.com",
          password: passwordHash,
          phone: "0987654321",
          id_role: 5,
          id_status: 1,
          id: 30,
        },
        {
          firstname: "Ahsoka",
          lastname: "Tano",
          gender: "F",
          birthdate: "1989-07-09",
          adress: "12 chemin du temple Jedi",
          city: "Coruscant",
          zipcode: "34567",
          email: "ahsoka@gmail.com",
          password: passwordHash,
          phone: "0987654321",
          id_role: 5,
          id_status: 1,
          id: 31,
        },
        {
          firstname: "Dhalsim",
          lastname: "Patel",
          gender: "M",
          birthdate: "1952-11-22",
          adress: "4 Yoga Fire Lane",
          city: "India",
          zipcode: "20001",
          email: "dhalsim@yoga.com",
          ine: "SF1234564D",
          password: passwordHash,
          phone: "0608102102",
          id_role: 5,
          id_status: 1,
          id: 32,
        },
        {
          firstname: "Eikichi",
          lastname: "Honda",
          gender: "M",
          birthdate: "1960-11-03",
          adress: "5 Sumo Stomp Road",
          city: "Tokyo",
          zipcode: "20002",
          email: "honda@sumo.com",
          ine: "SF1234565E",
          password: passwordHash,
          phone: "0608202202",
          id_role: 5,
          id_status: 1,
          id: 33,
        },
        {
          firstname: "Guile",
          lastname: "Nash",
          gender: "M",
          birthdate: "1960-12-23",
          adress: "6 Sonic Boom Boulevard",
          city: "USA",
          zipcode: "20003",
          email: "guile@airforce.com",
          ine: "SF1234566F",
          password: passwordHash,
          phone: "0608302302",
          id_role: 5,
          id_status: 1,
          id: 34,
        }
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    // await queryInterface.sequelize.query('TRUNCATE TABLE users');
  },
};
