"use strict";
const bcrypt = require("bcrypt");

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    const passwordHash = await bcrypt.hash("examplePassword", 10);
    await queryInterface.bulkInsert(
      "users",
      [
        // élèves
        {
          firstname: "Luke",
          lastname: "Skywalker",
          gender: "M",
          birthdate: "1990-01-01",
          adress: "1 rue de la paix",
          city: "Paris",
          zipcode: "75000",
          email: "luke@gmail.com",
          ine: "1234567891C",
          password: passwordHash,
          phone: "0606060606",
          // id_class: 1,
          // id_establishment : 1,
          id_role: 3,
          first_tutor: 2,
          second_tutor: 3,
        },
        // tuteurs
        {
          firstname: "Anakin",
          lastname: "Skywalker",
          gender: "M",
          birthdate: "1988-01-31",
          adress: "10 rue des bois",
          city: "Marseille",
          zipcode: "13000",
          email: "anakin@gmail.com",
          password: passwordHash,
          phone: "0690486933",
          // id_establishment : 1,
          // id_class : 1,
          id_role: 2,
        },
        {
          firstname: "Padmé",
          lastname: "Amidala",
          gender: "F",
          birthdate: "1984-09-11",
          adress: "3 rue du Pont",
          city: "Lyon",
          zipcode: "69000",
          email: "padme@gmail.com",
          password: passwordHash,
          phone: "0676341346",
          // id_establishment : 1,
          //id_class: 1,
          id_role: 2,
        },
        // admin
        {
          firstname: "Maitre",
          lastname: "Yoda",
          gender: "M",
          birthdate: "1984-06-29",
          adress: "4 chemin des pres",
          city: "Rouen",
          zipcode: "76000",
          email: "yoda@gmail.com",
          password: passwordHash,
          phone: "0712345678",
          // id_establishment : 1,
          //id_class: 1,
          id_role: 4,
        },
        // professeurs
        {
          firstname: "Obi-Wan",
          lastname: "Kenobi",
          gender: "M",
          birthdate: "1980-03-03",
          adress: "150 avenue des champs",
          city: "Bordeaux",
          zipcode: "33000",
          email: "obiwan@gmail.com",
          password: passwordHash,
          phone: "0789098754",
          ine: "1234567891E",
          // id_establishment : 1,
          //id_class: 1,
          id_role: 5,
          id_status: 1,
        },
        {
          firstname: "Leia",
          lastname: "Organa",
          gender: "F",
          birthdate: "1986-10-21",
          adress: "5 rue de la Liberté",
          city: "Tatooine",
          zipcode: "12345",
          email: "leia@gmail.com",
          password: passwordHash,
          phone: "0987654321",
          id_role: 5,
          id_status: 1,
        },
        {
          firstname: "Han",
          lastname: "Solo",
          gender: "M",
          birthdate: "1982-05-12",
          adress: "15 boulevard des étoiles",
          city: "Coruscant",
          zipcode: "54321",
          email: "han@gmail.com",
          password: passwordHash,
          phone: "0987654321",
          id_role: 5,
          id_status: 1,
        },
        {
          firstname: "Chewbacca",
          lastname: "Chewie",
          gender: "M",
          birthdate: "1995-11-15",
          adress: "8 allée des wookies",
          city: "Kashyyyk",
          zipcode: "67890",
          email: "chewie@gmail.com",
          password: passwordHash,
          phone: "0987654321",
          id_role: 5,
          id_status: 1,
        },
        {
          firstname: "Lando",
          lastname: "Calrissian",
          gender: "M",
          birthdate: "1981-12-25",
          adress: "20 rue du jeu de sabacc",
          city: "Bespin",
          zipcode: "98765",
          email: "lando@gmail.com",
          password: passwordHash,
          phone: "0987654321",
          id_role: 5,
          id_status: 1,
        },
        {
          firstname: "Ahsoka",
          lastname: "Tano",
          gender: "F",
          birthdate: "1989-07-09",
          adress: "12 chemin du temple Jedi",
          city: "Coruscant",
          zipcode: "34567",
          email: "ahsoka@gmail.com",
          password: passwordHash,
          phone: "0987654321",
          id_role: 5,
          id_status: 1,
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    // await queryInterface.sequelize.query('TRUNCATE TABLE users');
  },
};
