"use strict";
const bcrypt = require("bcrypt");

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    const passwordHash = await bcrypt.hash("examplePassword", 10);
    await queryInterface.bulkInsert(
      "users",
      [
        {
          firstname: "John",
          lastname: "Doe",
          gender: "M",
          birthdate: "1990-01-01",
          adress: "1 rue de la paix",
          city: "Paris",
          zipcode: "75000",
          email: "toto@gmail.com",
          password: passwordHash,
          phone: "0606060606",
          // id_establishment : 1,
          id_role: 2,
          id_status: 1,
        },
        {
          firstname: "Jeanne",
          lastname: "Doe",
          gender: "F",
          birthdate: "1988-01-31",
          adress: "10 rue des bois",
          city: "Marseille",
          zipcode: "13000",
          email: "toto@does.pinh",
          password: passwordHash,
          phone: "0690486933",
          // id_establishment : 1,
          // id_class : 1,
          id_role: 2,
          id_status: 1,
        },
        {
          firstname: "Sergine",
          lastname: "Delattre",
          gender: "F",
          birthdate: "1984-09-11",
          adress: "3 rue du Pont",
          city: "Lyon",
          zipcode: "69000",
          email: "Sergined-gameuse76@lamanu.pinh",
          password: passwordHash,
          phone: "0676341346",
          ine: "1234567891C",
          first_tutor: 1,
          second_tutor: 2,
          // id_establishment : 1,
          //id_class: 1,
          id_role: 3,
          id_status: 1,
        },
        {
          firstname: "Julien",
          lastname: "Montagne",
          gender: "M",
          birthdate: "1984-06-29",
          adress: "4 chemin des pres",
          city: "Rouen",
          zipcode: "76000",
          email: "LeMontagnard@lamanu.pinh",
          password: passwordHash,
          phone: "0712345678",
          ine: "1234567891D",
          first_tutor: 1,
          second_tutor: 2,
          // id_establishment : 1,
          //id_class: 1,
          id_role: 3,
          id_status: 1,
        },
        {
          firstname: "Sabrina",
          lastname: "Cuviller",
          gender: "F",
          birthdate: "1980-03-03",
          adress: "150 avenue des champs",
          city: "Bordeaux",
          zipcode: "33000",
          email: "SabroLaser@lamanu.pinh",
          password: passwordHash,
          phone: "0789098754",
          ine: "1234567891E",
          first_tutor: 1,
          second_tutor: 2,
          // id_establishment : 1,
          //id_class: 1,
          id_role: 3,
          id_status: 1,
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    // await queryInterface.sequelize.query('TRUNCATE TABLE users');
  },
};
